force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/MaxPay__c.field-meta.xml
<CustomField>
    <fullName>MaxPay__c</fullName>
    <label>Max Pay</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/MinPay__c.field-meta.xml
<CustomField>
    <fullName>MinPay__c</fullName>
    <label>Min Pay</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/OpenDate__c.field-meta.xml
<CustomField>
    <fullName>OpenDate__c</fullName>
    <label>Open Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NewPosition</fullName>
                <default>true</default>
                <label>New Position</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>PendingApproval</fullName>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>ClosedNotApproved</fullName>
                <label>Closed - Not Approved</label>
            </value>
            <value>
                <fullName>ClosedFilled</fullName>
                <label>Closed - Filled</label>
            </value>
            <value>
                <fullName>OpenApproved</fullName>
                <label>Open Approved</label>
            </value>
            <value>
                <fullName>ClosedCanceled</fullName>
                <label>Closed Canceled</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PositionSummaryController.cls
public class PositionSummaryController {
    
    public List<AggregateResult> lstSummary{get;set;}
    public List<Position__c> lstPosition{get;set;}
    public String positionName{get;set;}
    public String positionId{get;set;}
    
    public PositionSummaryController(){
        lstPosition = [SELECT Name, MaxPay__c, MinPay__c, Status__c, OpenDate__c, CloseDate__c
                       FROM Position__c];
     /*   if(lstPosition.size() > 0){
            for(Position__c objPosition : lstPosition){
                System.debug('Position Record : '+ lstPosition);
            }
        }*/
        lstSummary = [ SELECT sum(MaxPay__c) Maximum, sum(MinPay__c) Mininum, Max(MaxPay__c) MaxPay, Min(MinPay__c)
                      MinPay, Count(Name) cnt FROM Position__c];
    }
    public pageReference PositionDetailPage(){
        //System.debug('Page Details....' + positionId);
        pageReference pg=Page.jobapplication;
        pg.getParameters().put('uniqueId', positionId);
        pg.getParameters().put('uniqueIdName', positionName);
        return pg;
    }
}