force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/MaxPay__c.field-meta.xml
<CustomField>
    <fullName>MaxPay__c</fullName>
    <label>Max Pay</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/MinPay__c.field-meta.xml
<CustomField>
    <fullName>MinPay__c</fullName>
    <label>Min Pay</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NewPosition</fullName>
                <default>true</default>
                <label>New Position</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>PendingApproval</fullName>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>ClosedNotApproved</fullName>
                <label>Closed - Not Approved</label>
            </value>
            <value>
                <fullName>ClosedFilled</fullName>
                <label>Closed - Filled</label>
            </value>
            <value>
                <fullName>OpenApproved</fullName>
                <label>Open Approved</label>
            </value>
            <value>
                <fullName>ClosedCanceled</fullName>
                <label>Closed Canceled</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PositionController.cls
public class PositionController{
    
   public List<WrapperPosition> lstWrapperPosition {get;set;} 
    public Position__c objpsn{get;set;}
    
    public PositionController(){
        reference(); 
    }
    
    public void Save(){
        objpsn = new Position__c();
        List<Position__c> lstPositionsDelete = new List<Position__c>();
        List<Position__c> lstPositionUpsert = new List<Position__c>();
        
        for(WrapperPosition wprObj : lstWrapperPosition){
            
            if(wprObj.Selected == true) {
                lstPositionsDelete.add(wprObj.objPosition);
                // System.debug('lstPositionsDelete :'+ lstPositionsDelete);
            }
            else{
                lstPositionUpsert.add(wprObj.objPosition);
                //  System.debug('lstPositionUpsert :'+ lstPositionUpsert);
            }
        } 
        if(lstPositionUpsert.size()>0){
            Upsert  lstPositionUpsert;
        }
        if(lstPositionsDelete.size()>0){
            delete lstPositionsDelete;
        }
        //insert objpsn;
        reference();
    }
    
    public void reference(){
        objpsn = new Position__c();
        lstWrapperPosition = new List<WrapperPosition>();
        List<Position__c> lstPosition = [SELECT Name, MaxPay__c, MinPay__c, Status__c FROM Position__c LIMIT 200];
        if ( lstPosition.size() > 0){
            
            for (Position__c objPosition : lstPosition){
                WrapperPosition objWrapperPosition = new WrapperPosition(objPosition);              
                lstWrapperPosition.add(objWrapperPosition);
            }
        }
        lstWrapperPosition.add(new WrapperPosition(objpsn));    
    }

    public class WrapperPosition {
        public Position__c objPosition{get;set;}
        public Boolean Selected{get;set;}
        
        public WrapperPosition(Position__c obj){
            this.objPosition = obj;
            Selected = false;
        }
    }
}