force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fee__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Duration</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <label>Fee</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>100000</fullName>
            </value>
            <value>
                <fullName>250000</fullName>
            </value>
            <value>
                <fullName>300000</fullName>
            </value>
            <value>
                <fullName>400000</fullName>
            </value>
            <value>
                <fullName>25000</fullName>
            </value>
            <value>
                <fullName>35000</fullName>
            </value>
            <value>
                <fullName>50000</fullName>
            </value>
            <value>
                <fullName>70000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>AJ-{000}</displayFormat>
        <label>Roll Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>States__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agra</fullName>
                <default>true</default>
                <label>Agra</label>
            </value>
            <value>
                <fullName>Ajmer</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Bhilwara</fullName>
            </value>
            <value>
                <fullName>Gurugram</fullName>
            </value>
            <value>
                <fullName>Jaipur</fullName>
            </value>
            <value>
                <fullName>Jind</fullName>
            </value>
            <value>
                <fullName>Lucknow</fullName>
            </value>
            <value>
                <fullName>Nagaur</fullName>
            </value>
            <value>
                <fullName>Surat</fullName>
            </value>
            <value>
                <fullName>Vadoara</fullName>
            </value>
            <value>
                <fullName>Indore</fullName>
            </value>
            <value>
                <fullName>Chandigarh</fullName>
            </value>
            <value>
                <fullName>New delhi</fullName>
            </value>
            <value>
                <fullName>North Delhi</fullName>
            </value>
            <value>
                <fullName>East Delhi</fullName>
            </value>
            <value>
                <fullName>Bhopal akki</fullName>
            </value>
            <value>
                <fullName>Raisen district</fullName>
            </value>
            <value>
                <fullName>Sehore district</fullName>
            </value>
            <value>
                <fullName>Vidisha district</fullName>
            </value>
            <value>
                <fullName>Firozabad</fullName>
            </value>
            <value>
                <fullName>Mainpuri</fullName>
            </value>
            <value>
                <fullName>Mathura</fullName>
            </value>
            <value>
                <fullName>Patiala</fullName>
            </value>
            <value>
                <fullName>Ludhiana</fullName>
            </value>
            <value>
                <fullName>Amritsar</fullName>
            </value>
            <value>
                <fullName>--None--</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/MDRCourse__c.field-meta.xml
<CustomField>
    <fullName>MDRCourse__c</fullName>
    <label>Course Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Course__c.StudentCount__c</field>
            <operation>lessThan</operation>
            <value>6</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/States__c.field-meta.xml
<CustomField>
    <fullName>States__c</fullName>
    <label>States</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>MP</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>UP</fullName>
            </value>
            <value>
                <fullName>--None--</fullName>
                <default>true</default>
                <label>--None--</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Duration.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 Year</fullName>
    </customValue>
    <customValue>
        <fullName>2 Year</fullName>
    </customValue>
    <customValue>
        <fullName>3 Year</fullName>
    </customValue>
    <customValue>
        <fullName>4 Year</fullName>
    </customValue>
    <customValue>
        <fullName>6 Year</fullName>
    </customValue>
    <customValue>
        <fullName>5 Year</fullName>
    </customValue>
    <masterLabel>Duration</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/StudentTry.cls
public class StudentTry {
    
    public StudentTry(){
       List<Course__c> lstCourses =new List<Course__c>([SELECT Id, Fee__c, Duration__c, Name FROM Course__c WHERE Name = 'MCA']);
        for ( Course__c obj : lstCourses){
            System.debug( obj.Id);
        }
       
        if ( lstCourses.size() > 0){
            ID acc= lstCourses[0].Id;
            System.debug('First Id :  ' + acc);
        }
       
        /*Course__c  cs =new Course__c();
        cs.Name='MCA';
        cs.Fee__c='300000';
        cs.Duration__c='3 Year';
        insert cs;*/
        
       Student__c st=new Student__c();
         st.FirstName__c='Rohit';
         st.LastName__c='Sharma';
         st.Gender__c='Male';
         st.ContactNumber__c='9828652314';
         st.Email__c='virats@gmail.com';
         st.City__c='Ajmer';
         st.States__c='Rajasthan';
         st.Fee__c=60000;
         st.MDRCourse__c=lstCourses[0].Id;
        //st.MDRCourse__c=cs;
          insert st;
    }
}