force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>AJ-{000}</displayFormat>
        <label>Roll Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/admissionDate__c.field-meta.xml
<CustomField>
    <fullName>admissionDate__c</fullName>
    <description>Created date</description>
    <formula>DATEVALUE( CreatedDate )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>admissionDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <description>Student full name</description>
    <formula>FirstName__c  &amp; &quot;, &quot; &amp;  LastName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StudentsListController.cls
public class StudentsListController {
    public List<WrapperStudent> lstWrapperStudents {get;set;}
    private List<Student__c> lstStudents;
    public String recordEditId {get;set;}
    public String recordDeleteId {get;set;}
   
    public StudentsListController(){
        recordEditId = '';
        recordDeleteId = '';
        lstWrapperStudents = new List<WrapperStudent>();
        lstStudents = [ SELECT Name, FullName__c, Gender__c,admissionDate__c 
                        FROM Student__c
                        ORDER By Name
                      ];
        // , course__r.course__c
       
        if ( lstStudents.size() > 0){
            for (Student__c objStudent : lstStudents){
              //System.debug('lstStudent :' + objStudent);
                WrapperStudent objWrapperStudent = new WrapperStudent(objStudent);              
                lstWrapperStudents.add(objWrapperStudent);
            }
        }
    }
         /* PageReference
            We will create an object of this PageRefernce Class
         */
    public PageReference editStudent(){
        System.debug('Edit Button Clicked....' + recordEditId);
      //PageReference pgEdit=new PageReference;
        PageReference  pgEdit=Page.editstudent;
        pgEdit.getParameters().put('uniqueId', recordEditId);
        return pgEdit;
      //return objPage;
      // return null; 
    }
   
    public PageReference deleteStudent(){
        System.debug('Delete Button Clicked....' + recordDeleteId);
        PageReference pgDelete=Page.deleteStudent;
        pgDelete.getParameters().put('uniqueId', recordDeleteId);
        return pgDelete;
    }
       
    public class WrapperStudent {
        public Student__c objStudent {get;set;}
        public Boolean selected {get;set;}
        public Integer days {get;set;}
       
        public WrapperStudent(Student__c obj){
            this.objStudent = obj;
            selected = false;
            if(obj.admissionDate__c != null)
            days = (obj.AdmissionDate__c).daysBetween(System.today());
            else
                days = 0;
        }
    }
}