force-app/main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Project Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Task__c/fields/Previous_Task__c.field-meta.xml
<CustomField>
    <fullName>Previous_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Task</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipLabel>Project Tasks (Previous Task)</relationshipLabel>
    <relationshipName>Project_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectTriggerHelper.cls
/*
* Name         : ProjectTriggerHelper
* Author       : Abdul Pathan
* Date         : 20 Feb, 2020
* Description  : Project(Parent) Record insert then Project_Task(Child) Record create (five record create)
*/

public class ProjectTriggerHelper {
    public static void insertProjectTasks(List<Project__c> projectList){
        
        List<Project_Task__c> projectTaskList = new List<Project_Task__c>();
        
        if(projectList.size() > 0){
            for(Project__c projectObj : projectList){          
                projectTaskList.add(new Project_Task__c(Project__c =projectObj.Id , Type__c = 'New Task'));
                projectTaskList.add(new Project_Task__c(Project__c =projectObj.Id , Type__c = 'Planning Phase'));
                projectTaskList.add(new Project_Task__c(Project__c =projectObj.Id , Type__c = 'Construction Work'));
                projectTaskList.add(new Project_Task__c(Project__c =projectObj.Id , Type__c = 'Completion Step'));
                projectTaskList.add(new Project_Task__c(Project__c =projectObj.Id , Type__c = 'Contract End'));
            }
        }
        
        
        // Insert  project Task Record
        if(projectTaskList.size() > 0){
            insert projectTaskList;
        }
        
        Integer count = 0;   // Index Count Previous Task
        List<Project_Task__c> projectTaskRecords = new List<Project_Task__c>();
        if(projectTaskList.size() > 0){
            for(Project_Task__c projectTaskObj : projectTaskList){
                
                if(projectTaskObj.Type__c != 'New Task' ){
                    projectTaskObj.Previous_Task__c = projectTaskList[count].id;
                    count++;
                    projectTaskRecords.add(projectTaskObj);
                }
            }
        }
        
        // update  Project Task Record
        if(projectTaskRecords.size() > 0){
            update projectTaskRecords;
        }
    }   
}