force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Accounts__c.field-meta.xml
<CustomField>
    <fullName>Accounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approve</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/claimApprovedRejectComponent.cls
// Author : Abdul Pathan
// Date : 07-Oct-2021
// Class :  claimApprovedRejectComponent
public class claimApprovedRejectComponent {
    @AuraEnabled(cacheable=true)
    public static List<Claim__c> setViewStat(String accountId) {
        List<Claim__c> claimRecords = [SELECT Id, Status__c, Owner.Name, CreatedBy.Name, Name, CreatedDate, LastModifiedDate, Accounts__r.Name 
                                       FROM Claim__c
                                       WHERE Accounts__c =: accountId AND Status__c =: 'Approve'
                                      ];
        return claimRecords;
    }
}
/*
@AuraEnabled 
public static Map<String, String> getStatusFieldValue(){
Map<String, String> options = new Map<String, String>();
Schema.DescribeFieldResult fieldResult = Claim__c.Status__c.getDescribe();
List<Schema.PicklistEntry> pValues = fieldResult.getPicklistValues();
for (Schema.PicklistEntry p: pValues) {
options.put(p.getValue(), p.getLabel());
}
System.debug('options' + options);
return options;
}
*/