force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approve</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClaimsHelper.cls
public class ClaimsHelper {
    public static void onAfterInsert(List<Claim__c> claimsList){
        if(claimsList.size() > 0){
            for(Claim__c claim : claimsList){
                if(claim.Status__c == 'Pending'){                  
                    Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
                    req.setComments('Submitting request for approval automatically using Trigger');
                    req.setObjectId(claim.Id);
                    req.setNextApproverIds(new Id[] {UserInfo.getUserId()});
                    Approval.ProcessResult approvalResult = Approval.process(req);
                    System.debug('offer submitted for approval successfully: '+ approvalResult .isSuccess());
                }
            }
        }
        
    }
}