force-app/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <label>Employees</label>
    <nameField>
        <label>Employees Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Employees__c.field-meta.xml
<CustomField>
    <fullName>Employees__c</fullName>
    <label>Employees</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Incident__c.field-meta.xml
<CustomField>
    <fullName>Incident__c</fullName>
    <label>Incident</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>new employee</fullName>
            </value>
            <value>
                <fullName>removed employee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmployeesTriggerHelperTest.cls
@isTest
private class EmployeesTriggerHelperTest {
    
    @TestSetUp static void testingTriggerEmployeeData (){
        
        List<Employees__c> lstemp = new List<Employees__c>();
        
        Employees__c emp1=new Employees__c();
        emp1.Name = 'Tarun';
        emp1.Status__c = 'active';
        lstemp.add(emp1);
        
        Employees__c emp2=new Employees__c();
        emp2.Name = 'Vikash';
        emp2.Status__c = 'Inactive';
        lstemp.add(emp2);
        
        insert lstemp;
        
        List<Log__c> lstLog=new List<Log__c>();
        
        Log__c logObj1 = new Log__c(Incident__c='New Employee', Employees__c=emp1.id);
        lstLog.add(logObj1);
        
        Log__c logObj2 = new Log__c(Incident__c='Removed Employee', Employees__c=emp2.id);
        lstLog.add(logObj2);
    }
    
    @isTest static void testDatas(){
        
        List<Employees__c> lstem=new List<Employees__c>();
        
        Employees__c em1= [select id from Employees__c where name = 'Vikash'];
        em1.Status__c = 'Inactive';
        lstem.add(em1);
        
        Employees__c em2= [select id from Employees__c where name = 'Tarun'];
        em2.Status__c = 'active';
        lstem.add(em2);
        
        update lstem;
    }
}