force-app/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <label>Employees</label>
    <nameField>
        <label>Employees Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Employees__c.field-meta.xml
<CustomField>
    <fullName>Employees__c</fullName>
    <label>Employees</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Incident__c.field-meta.xml
<CustomField>
    <fullName>Incident__c</fullName>
    <label>Incident</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>new employee</fullName>
            </value>
            <value>
                <fullName>removed employee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmployeesTriggerHelper.cls
public class EmployeesTriggerHelper {
    
    public   static void upDateEmployees(Set<String> setEmp){
        List<Log__c> lstLog = new List<Log__c>();
        List<Employees__c>  lstEmployees = [SELECT Id, Status__c , (SELECT  Employees__c, Incident__c FROM Logs__r) FROM Employees__c
                                            WHERE Id in : setEmp];
        if(lstEmployees.size() > 0){
            
            for(Employees__c emp : lstEmployees){
                if(emp.Logs__r.size() > 0){
                    for(Log__c log : emp.Logs__r){
                        if(emp.Status__c == 'Active'){
                            log.Incident__c = 'new employee';
                            lstLog.add(log);
                        }
                        if(emp.Status__c == 'Inactive'){
                            log.Incident__c = 'removed employee';
                            lstLog.add(log);
                        }
                    }
                }
                else{
                    Log__c objLog = new Log__c();
                    objLog.Employees__c = emp.id;
                    if(emp.Status__c == 'Active'){
                        objLog.Incident__c = 'new employee';
                        lstLog.add(objLog);
                    }
                    if(emp.Status__c == 'Inactive'){
                        objLog.Incident__c = 'removed employee';
                        lstLog.add(objLog);
                    }
                    insert objLog;
                }
            }
        }
        if(lstLog.size() > 0){
            update lstLog;
        }
        
    }
}