force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <description>Represents an applicant who might apply for
one or more positions.</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobApplication__c/JobApplication__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JobApplications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobApplication__c/fields/AverageRating__c.field-meta.xml
<CustomField>
    <fullName>AverageRating__c</fullName>
    <formula>TotalRating__c  /  NumberOfReviews__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Average Rating</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>JobApplications</relationshipLabel>
    <relationshipName>JobApplications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/fields/CoverLetter__c.field-meta.xml
<CustomField>
    <fullName>CoverLetter__c</fullName>
    <label>Cover Letter</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/fields/NumberOfReviews__c.field-meta.xml
<CustomField>
    <fullName>NumberOfReviews__c</fullName>
    <label>Number of Reviews</label>
    <summaryForeignKey>Review__c.JobApplication__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/fields/TotalRating__c.field-meta.xml
<CustomField>
    <fullName>TotalRating__c</fullName>
    <label>Total Rating</label>
    <summarizedField>Review__c.Rating__c</summarizedField>
    <summaryForeignKey>Review__c.JobApplication__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NewPosition</fullName>
                <default>true</default>
                <label>New Position</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>PendingApproval</fullName>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>ClosedNotApproved</fullName>
                <label>Closed - Not Approved</label>
            </value>
            <value>
                <fullName>ClosedFilled</fullName>
                <label>Closed - Filled</label>
            </value>
            <value>
                <fullName>OpenApproved</fullName>
                <label>Open Approved</label>
            </value>
            <value>
                <fullName>ClosedCanceled</fullName>
                <label>Closed Canceled</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationListController.cls
public class JobApplicationListController {
    public List<WrapperJobApplication> lstWrapperJobApplication{get;set;}
    private List<JobApplication__c> lstJobApplication;
    
    public JobApplicationListController(){
        lstWrapperJobApplication = new  List<WrapperJobApplication>();
        lstJobApplication = [SELECT Name, Position__c, Candidate__c , Status__c, TotalRating__c,CoverLetter__c,NumberOfReviews__c, AverageRating__c
                             FROM JobApplication__c Limit 10
                            ];
        if(lstJobApplication.size() > 0){
            for(JobApplication__c objJobApplication : lstJobApplication){
                WrapperJobApplication objWrapperJobApplication = new WrapperJobApplication(objJobApplication);              
                lstWrapperJobApplication.add(objWrapperJobApplication);
            }
        }
    }
    public void EditJobApplication(){}
    public void DeleteJobApplication(){}
    
    public class WrapperJobApplication{
        public JobApplication__c objJobApplication {get;set;}
        public Boolean Selected{get;set;}
        
        public WrapperJobApplication(JobApplication__c obj){
            this.objJobApplication = obj;
            Selected = false;
        }
    }
    
}