force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <description>Represents an applicant who might apply for
one or more positions.</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobApplication__c/JobApplication__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JobApplications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobApplication__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>JobApplications</relationshipLabel>
    <relationshipName>JobApplications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/JobApplicationController.cls
public class JobApplicationController {
    
    public List<AggregateResult> Result{get;set;}
    public List<JobApplication__c> lstJobApplication{get;set;}
    public String recordId;
    public String recordName{get;set;}
    
    public JobApplicationController(){
        recordId = ApexPages.currentPage().getParameters().get('uniqueId');
        recordName = ApexPages.currentPage().getParameters().get('uniqueIdName');
        System.debug('Record id ' + recordId);
        
        Result = [SELECT Count(Id) cnt , Candidate__r.City__c city, Position__r.Name
                  FROM JobApplication__c
                  WHERE Position__c = : recordId OR Position__c = : recordName
                  group by Candidate__r.City__c, Position__r.Name
                 ];
        if(Result.size() == 0){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'No Record available'));
        }
      /*  System.debug('Result List ' + Result);  
        if(Result.size() > 0){
            for(AggregateResult obj : Result){
                System.debug('Result Lists ' + obj);
            }
        } */
    }
  public PageReference CanselButton(){
      PageReference pg=page.positionsummary;
      return pg;
    }
    
}