force-app/main/default/objects/Route_Station__c/Route_Station__c.object-meta.xml
<CustomObject>
    <label>Route Station</label>
    <nameField>
        <label>Route Station Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Stations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Station__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <label>Distance</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route_Station__c/fields/Main_Route__c.field-meta.xml
<CustomField>
    <fullName>Main_Route__c</fullName>
    <label>Main Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Route Stations</relationshipLabel>
    <relationshipName>Route_Stations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RouteMapModel.cls
global class RouteMapModel {
    public String requestStatus;
    public String errorMessage;
    public String source{get;set;}
    public String destination{get;set;}
    public String highway{get;set;}
    public Decimal totalDistance;
    public String walking, bicycle, car, train, plane;
    public Double walkingTime, bicycleTime, carTime, trainTime, planeTime;
}

/*
    @HttpGet
    global static Route_Station__c doGetRouteStations(){
         // RestRequest request = RestContext.request;
         Route_Station__c result =  [SELECT Id, Previous_Station__c, Distance__c, Main_Route__c, Name
                                    FROM Route_Station__c WHERE Id = : 'a0Q2w0000006fRHEAY'
                                   ];
        return result;*/
       /* Route_Station__c station = new Route_Station__c();
            map<String, String> paramMap=new RestContext.request.params;
            String stationId = paramMap.get('id');
            station =  [SELECT Id, Previous_Station__c, Distance__c, Main_Route__c, Name
                        FROM Route_Station__c WHERE Id = : 'a0Q2w0000006fRHEAY'
                       ];
            return station;*/
 /*   }
    @httpPost
    global static String doCreateRouteStations(){
        return 'a';
    }
    @httpDelete
    global static String doDeleteRouteStations(){
        return 'b';
    }
    @HttpPut
    global static String doputRouteStations(){
        return 'c';
    }    
    @httpPatch
    global static String doUpsertRouteStations(){
        return 'd';
    }
 */
// /services/apexrest/iBirds/BookManagement/