force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Owner__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Project Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Positive</fullName>
    </customValue>
    <customValue>
        <fullName>Negative</fullName>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectEmailTemplatesController.cls
/*
* @Name         : ProjectEmailTemplatesController
* @Author       : Abdul Pathan
* @Date         : 20 Feb, 2020
* @Description  : Project Tasks compeleted then send email  (component Name = projectemailtemplates)
*/
public class ProjectEmailTemplatesController{
    public Boolean projectTaskBoolean{get;set;}
    public String ownerName{get;set;}
    public String projectId{get;set;}
    public List<Project_Task__c> lstProjectTask{get;set;}
    public List<Project_Task__c> lstProjectTaskName{get;set;}
    
    public ProjectEmailTemplatesController(){
        //  ProjectTasks()
    }
    
    // ProjectTasks Method
    public List<Project_Task__c> getProjectTasks(){
        lstProjectTask = [SELECT Id,  Project__c, CreatedDate, Completion_Date__c, Type__c, Owner.Name ,
                          Project__r.Project_Owner__c, Project__r.Project_Owner__r.Name  
                          FROM Project_Task__c
                          where Project__c =: projectId AND Completed__c = true
                         ];
        return lstProjectTask;
    }
    
    public String getProjectTaskName(){
        lstProjectTaskName = [SELECT id, Type__c, Owner.Name FROM Project_Task__c   
                              where Project__c =: projectId 
                             ];
        for(Project_Task__c objProjecttask : lstProjectTaskName){
            if(objProjecttask.Type__c == 'Contract End'){	
                ownerName = objProjecttask.Owner.Name;
            }
        }
        return ownerName;
    }
}