force-app/main/default/objects/Motor_Parts__mdt/Motor_Parts__mdt.object-meta.xml
<CustomObject>
    <label>Motor Parts</label>
    <pluralLabel>Motor Parts</pluralLabel>
</CustomObject>

force-app/main/default/objects/Motor_Parts__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bike</fullName>
                <default>true</default>
                <label>Bike</label>
            </value>
            <value>
                <fullName>Car</fullName>
            </value>
            <value>
                <fullName>Scooter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Required_Parts__c/Required_Parts__c.object-meta.xml
<CustomObject>
    <label>Required Parts</label>
    <nameField>
        <label>Required Parts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required_Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Required_Parts__c/fields/Motor_Type__c.field-meta.xml
<CustomField>
    <fullName>Motor_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motor Type</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Required_Parts</relationshipLabel>
    <relationshipName>Required_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductHelper.cls
/*
* Author  :  Abdul Pathan
* Name    :  ProductHelper
* Date    :  09, Nov 2021
* Description  : I create the product record, then automatically five child records (Required Pards) created
*/
public class ProductHelper {
    //afterInsert
    public static void onAfterInsert(List<Product2> productRecords){
        afterInsert(productRecords);
    }
    
    public static void afterInsert(List<Product2> productRecords){
        List<Required_Parts__c> requiredPardsList = new List<Required_Parts__c>();
        Map<Id, String> mapProduct = new Map<Id, String>();
        Map<String, List<Motor_Parts__mdt>> mapMotorParts = new Map<String, List<Motor_Parts__mdt>>();
        
        if(productRecords.size() > 0){
            for(Product2 product : productRecords){ 
                String recordTypeName = Schema.SObjectType.Product2.getRecordTypeInfosById().get(product.RecordTypeId).getName();
                mapProduct.put(product.Id, recordTypeName);
            }
        }
        if(mapProduct.size() > 0 ){            
            for(Motor_Parts__mdt moterParts : [SELECT Id, Cost__c, Type__c, Label FROM Motor_Parts__mdt WHERE Type__c IN : mapProduct.values()]){  
                if(mapMotorParts.containsKey(moterParts.Type__c)){
                    List<Motor_Parts__mdt> motorPartList = mapMotorParts.get(moterParts.Type__c);
                    motorPartList.add(moterParts);
                    mapMotorParts.put(moterParts.Type__c, motorPartList);
                }else{
                    mapMotorParts.put(moterParts.Type__c, new List<Motor_Parts__mdt>{moterParts});
                }
            }
            for(Id product : mapProduct.keyset()){
                if(mapProduct.containskey(product) && mapMotorParts.containsKey(mapProduct.get(product))){
                    for(Motor_Parts__mdt metaDataObj : mapMotorParts.get(mapProduct.get(product))){
                        requiredPardsList.add(new Required_Parts__c(Motor_Type__c = product , Name = metaDataObj.Label, Cost__c = metaDataObj.Cost__c));
                    }
                }
            }
        }
        if(requiredPardsList.size() > 0){
            Insert requiredPardsList; // Insert RequiredParts Records
        }
    }
}